---
title: "An Exploratory Data Analysis of Environmental Impacts of Bitcoin Mining"
author: "Tushar, Kusum, Brian"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Abstract
This abstract summarizes an exploratory data analysis (EDA) project that examines environmental impacts of Bitcoin Mining using dataset which contains 15 fields and a total of 4815 records. This data analysis examines the variations in electricity consumption and CO2 emissions on a per day basis resulting from Bitcoin mining. This analysis investigates the impact of various variables on the CO2 emissions intensity associated with Bitcoin and also explores how Bitcoin mining activity (Bitcoin network hashrate) varies by region. To assess the relationship between Bitcoin and its environmental impact, the dataset is utilized to conduct a series of analyses in the following order: Time series plot, distribution of variables, outlier detection, variable relationships, and spatial analysis. Overall, this analysis provides insights into how Bitcoin mining has affected the environment and can be helpful for shaping future policies to mitigate environmental pollution caused by Bitcoin mining.

# Introduction
Bitcoin mining requires miners to solve mathematical puzzles known as the proof of work. The reason Bitcoin mining consumes a significant amount of electricity is primarily due to the energy-intensive nature of the Proof of Work (PoW) consensus algorithm it uses.The competitive mining drives miners to use increasingly powerful and energy-hungry hardware to gain a competitive edge. The ASICs are highly efficient at solving the PoW puzzles but are power-hungry machines that consume substantial electricity.

### Bitcoin Mining Process

* Bitcoin mining involves use of specialized hardware, such as ASICs or GPUs to perform the Proof of Work calculations.
* These devices are energy-intensive and are designed to perform hash computations quickly. 
* In this research, the aim is to comprehensively analyze the relationship between Bitcoin mining and its environmental consequences through exploratory data and statistical analysis. 

### SMART Questions

1. What are the impacts of different variables on the CO2 emission intensity?
2. How does the Bitcoin mining activity (network hash rate) vary with regional variations?

### Methodology

1. Time series and stationarity analysis
2. Distribution of variables 
3. Outlier detection 
4. Variable relationships 
5. Spatial analysis 

# 1. Data 

The raw data contains 15 fields and a total of 4815 records from July 18, 2010 to Sep 22, 2023. Separate geolocational data consisting of country-wise monthly hash rate from Sep 2019 to Jan 2019. Among the 15 variables, some are generally reported with an uncertainty i.e. the lower and upper bounds and a best estimate (guess). From the total 15 columns, 7 columns were removed and only the best estimate values for such variables have been retained. The target variable of interest is the emission intensity of CO2.

* Emission intensity :  Emission intensity measures the amount of greenhouse gas emissions (e.g., CO2) produced per unit of energy generated. It's often used to compare the environmental impact of different energy sources or activities.
* Hashrate :  The Bitcoin hashrate is a measure of the computational power and processing capacity of the Bitcoin network.     It represents the total number of hash operations (cryptographic calculations) that the network can perform per second.
* Annualized consumption guess: This likely refers to an estimate of the annual energy consumption for a specific device, system, or operation. It's an approximation of how much electricity will be used over a year.


## References

Bitcoin Network Hash Rate, NASDAQ 2023, https://data.nasdaq.com/data/BCHAIN/HRATE-bitcoin-hash-rate

Cambridge Bitcoin Electricity Consumption Index 2023, https://ccaf.io/cbnsi/cbeci.

